Repository Soft-Gallery/issue-management-backEnd, pull requests merged in 2024-05, with the labels that each got.

#3 [Feat#1] MVC 패턴 적용 및 DB 연동
  .gitignore
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/issue/IssueController.java
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/project/ProjectController.java
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/user/UserController.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/CommentDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/IssueDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/ProjectDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/StatisticsDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/UserDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/AdminEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/CommentEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/DeveloperEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/IssueEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/PLEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/ProjectEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/StatisticsEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/TesterEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/UserEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/repository/IssueRepository.java
  src/main/java/com/softgallery/issuemanagementbackEnd/repository/ProjectRepository.java
  src/main/java/com/softgallery/issuemanagementbackEnd/repository/UserRepository.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/issue/IssueService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/issue/IssueServiceIF.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/project/ProjectService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/project/ProjectServiceIF.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/user/UserService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/user/UserServiceIF.java
  src/main/resources/application.properties
Labels: enhancement

#13 [Feat#9] Comment 작성 기능 구현
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/comment/CommentController.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/CommentEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/exception/ObjectNotFoundException.java
  src/main/java/com/softgallery/issuemanagementbackEnd/repository/CommentRepository.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/comment/CommentService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/comment/CommentServiceIF.java
Labels: enhancement

#19 Feat#15
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/project/ProjectController.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/ProjectDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/ProjectEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/project/ProjectService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/project/ProjectServiceIF.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/project/ProjectState.java
Labels: bug

#20 Feat#17
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/ProjectMemberEntity.java
Labels: enhancement

#24 Feat#17
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/project/ProjectController.java
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/projectMember/ProjectMemberController.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/ProjectDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/ProjectMemberDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/UserDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/exception/ProjectMemberNotFoundException.java
  src/main/java/com/softgallery/issuemanagementbackEnd/repository/ProjectMemberRepository.java
  src/main/java/com/softgallery/issuemanagementbackEnd/repository/ProjectRepository.java
  src/main/java/com/softgallery/issuemanagementbackEnd/repository/UserRepository.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/project/ProjectService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/project/ProjectServiceIF.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/projectMember/ProjectMemberService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/projectMember/ProjectMemberServiceIF.java
Labels: enhancement

#28 [Feat#22] 이슈 통계정보 생성 및 전달
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/statistics/StatisticsController.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/StatisticsDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/StatisticsEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/repository/StatisticsRepository.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/issue/MainCause.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/statistics/StatisticsService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/statistics/StatisticsServiceIF.java
Labels: enhancement

#29 [Refactor#27] Comment CRUD 로직 수정
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/comment/CommentController.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/CommentDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/comment/CommentService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/comment/CommentServiceIF.java
Labels: enhancement

#33 [Bug#32] Statistics logic 임시 수정
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/statistics/StatisticsController.java
  src/main/java/com/softgallery/issuemanagementbackEnd/repository/StatisticsRepository.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/statistics/StatisticsService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/statistics/StatisticsServiceIF.java
Labels: bug

#34 [Feat#30] API문서화를 위한 Swagger 추가
  build.gradle
  src/main/java/com/softgallery/issuemanagementbackEnd/config/SecurityConfig.java
  src/main/java/com/softgallery/issuemanagementbackEnd/config/SwaggerConfig.java
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/issue/IssueController.java
Labels: enhancement

#35 [Refactor#31] 이슈 통계정보 CRUD 개선 (1차)
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/issue/IssueController.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/IssueDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/StatisticsDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/IssueEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/StatisticsEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/issue/IssueService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/statistics/StatisticsService.java
Labels: enhancement

#42 [Bug#37] dev 브랜치 내 버그 수정
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/statistics/StatisticsController.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/IssueDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/StatisticsDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/StatisticsEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/repository/StatisticsRepository.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/issue/IssueService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/statistics/StatisticsService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/statistics/StatisticsServiceIF.java
Labels: bug, enhancement

#43 [Feat#41] DB 구조 변경 및 Foreign Key 설정
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/statistics/StatisticsController.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/StatisticsDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/IssueEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/entity/StatisticsEntity.java
  src/main/java/com/softgallery/issuemanagementbackEnd/repository/IssueRepository.java
  src/main/java/com/softgallery/issuemanagementbackEnd/repository/StatisticsRepository.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/issue/IssueService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/issue/IssueServiceIF.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/statistics/StatisticsService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/statistics/StatisticsServiceIF.java
Labels: enhancement

#46 [Refactor#45] 프로젝트 관리 기능 수정
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/project/ProjectController.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/project/ProjectService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/project/ProjectServiceIF.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/projectMember/ProjectMemberService.java
Labels: enhancement

#52 [Config#51] 기존 테스트 코드 주석 처리 및 일부 수정
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/chat_gpt/ChatGptController.java
  src/main/java/com/softgallery/issuemanagementbackEnd/controller/project_member/ProjectMemberController.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/chat_gpt/ChatGptRequestDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/chat_gpt/ChatGptResponseDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/chat_gpt/Choice.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/chat_gpt/Message.java
  src/main/java/com/softgallery/issuemanagementbackEnd/dto/chat_gpt/QuestionRequestDTO.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/chatGpt/ChatGptService.java
  src/main/java/com/softgallery/issuemanagementbackEnd/service/chatGpt/ChatGptServiceIF.java
  src/test/java/com/softgallery/issuemanagementbackEnd/authentication/JWTUtilTest.java
  src/test/java/com/softgallery/issuemanagementbackEnd/service/user/IDRuleValidator.java
  src/test/java/com/softgallery/issuemanagementbackEnd/service/user/IDRuleValidatorTest.java
  src/test/java/com/softgallery/issuemanagementbackEnd/service/user/UserServiceTest.java
Labels: enhancement
